package View;

import Objetos.Produto;
import Conexões.MySQL;

/**
 *
 * @author eduar
 */
public class MenuProd_Teste extends javax.swing.JFrame {

    /**
     * Creates new form MenuProd_Teste
     */
    public MenuProd_Teste() {
        initComponents();
    }

    Prod_View pv = new Prod_View();
    MySQL conecta = new MySQL();
    Produto prod = new Produto();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imagemTeste = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelTit = new javax.swing.JPanel();
        labFiltro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelFiltro = new javax.swing.JPanel();
        cbDeparts = new javax.swing.JComboBox<>();
        labelVMax = new javax.swing.JLabel();
        spiVMax = new javax.swing.JSpinner();
        labelVMin = new javax.swing.JLabel();
        spiVMin = new javax.swing.JSpinner();
        labelQuant = new javax.swing.JLabel();
        sliQuant = new javax.swing.JSlider();
        panelFiltrar = new javax.swing.JPanel();
        buttonFiltrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        FecharItem = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenu();
        mitemCadastrar = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        View_Prod = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        imagemTeste.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Pictures\\PokéBattle\\PokeBattle Interface1.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setLocation(new java.awt.Point(233, 84));
        setMaximumSize(new java.awt.Dimension(900, 630));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        panelTit.setBackground(new java.awt.Color(20, 20, 20));
        panelTit.setForeground(new java.awt.Color(20, 20, 20));
        panelTit.setPreferredSize(new java.awt.Dimension(0, 142));

        labFiltro.setFont(new java.awt.Font("Sitka Small", 1, 30)); // NOI18N
        labFiltro.setForeground(new java.awt.Color(217, 182, 255));
        labFiltro.setText("Filtro");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\MenuProd\\MenuProd3.png")); // NOI18N

        javax.swing.GroupLayout panelTitLayout = new javax.swing.GroupLayout(panelTit);
        panelTit.setLayout(panelTitLayout);
        panelTitLayout.setHorizontalGroup(
            panelTitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(labFiltro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTitLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelTitLayout.setVerticalGroup(
            panelTitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );

        panelFiltro.setBackground(new java.awt.Color(109, 98, 131));
        panelFiltro.setPreferredSize(new java.awt.Dimension(250, 431));

        cbDeparts.setFont(new java.awt.Font("Traveling _Typewriter", 0, 15)); // NOI18N
        cbDeparts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos Departamentos", "Armas", "Munições", "Consumíveis", "Especiais" }));
        cbDeparts.setPreferredSize(new java.awt.Dimension(204, 30));

        labelVMax.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        labelVMax.setForeground(new java.awt.Color(20, 20, 20));
        labelVMax.setText("Valor Máximo:");

        spiVMax.setFont(new java.awt.Font("Traveling _Typewriter", 0, 16)); // NOI18N
        spiVMax.setModel(new javax.swing.SpinnerNumberModel(8000, 300, 8000, 100));
        spiVMax.setPreferredSize(new java.awt.Dimension(100, 30));

        labelVMin.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        labelVMin.setForeground(new java.awt.Color(20, 20, 20));
        labelVMin.setText("Valor Mínimo:");

        spiVMin.setFont(new java.awt.Font("Traveling _Typewriter", 0, 16)); // NOI18N
        spiVMin.setModel(new javax.swing.SpinnerNumberModel(300, 300, 7700, 100));
        spiVMin.setPreferredSize(new java.awt.Dimension(100, 30));

        labelQuant.setFont(new java.awt.Font("Sitka Small", 1, 19)); // NOI18N
        labelQuant.setForeground(new java.awt.Color(20, 20, 20));
        labelQuant.setText("Quantidade");
        labelQuant.setPreferredSize(new java.awt.Dimension(112, 24));
        labelQuant.setRequestFocusEnabled(false);

        sliQuant.setMajorTickSpacing(5);
        sliQuant.setMaximum(30);
        sliQuant.setMinorTickSpacing(1);
        sliQuant.setPaintTicks(true);
        sliQuant.setSnapToTicks(true);
        sliQuant.setToolTipText("");
        sliQuant.setValue(15);
        sliQuant.setPreferredSize(new java.awt.Dimension(190, 45));

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbDeparts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(labelQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sliQuant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFiltroLayout.createSequentialGroup()
                        .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVMax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spiVMax, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spiVMin, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cbDeparts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spiVMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVMax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVMin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiVMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(labelQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sliQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelFiltrar.setBackground(new java.awt.Color(20, 20, 20));
        panelFiltrar.setPreferredSize(new java.awt.Dimension(0, 154));

        buttonFiltrar.setBackground(new java.awt.Color(217, 182, 255));
        buttonFiltrar.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        buttonFiltrar.setForeground(new java.awt.Color(20, 20, 20));
        buttonFiltrar.setText("Filtrar");
        buttonFiltrar.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\MenuProd\\MenuProd3.png")); // NOI18N

        javax.swing.GroupLayout panelFiltrarLayout = new javax.swing.GroupLayout(panelFiltrar);
        panelFiltrar.setLayout(panelFiltrarLayout);
        panelFiltrarLayout.setHorizontalGroup(
            panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(buttonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelFiltrarLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelFiltrarLayout.setVerticalGroup(
            panelFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrarLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(buttonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(4, 573));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\MenuProd\\MenuProd4.png")); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setMinimumSize(new java.awt.Dimension(4, 568));
        jLabel4.setPreferredSize(new java.awt.Dimension(4, 573));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setBackground(new java.awt.Color(20, 20, 20));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(20, 20, 20));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(238, 238, 238));
        jPanel2.setPreferredSize(new java.awt.Dimension(646, 1500));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\MenuProd\\MenuProd5.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jMenuBar1.setBackground(new java.awt.Color(187, 187, 187));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Programa");

        FecharItem.setText("Fechar");
        FecharItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharItemActionPerformed(evt);
            }
        });
        jMenu1.add(FecharItem);

        jMenuBar1.add(jMenu1);

        menuCliente.setText("Cliente");

        jMenuItem1.setText("Carrinho");
        menuCliente.add(jMenuItem1);

        jMenuItem2.setText("Lista de Desejos");
        menuCliente.add(jMenuItem2);

        jMenuBar1.add(menuCliente);

        menuFuncionario.setText("Funcionário");

        mitemCadastrar.setText("Cadastrar");
        mitemCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCadastrarActionPerformed(evt);
            }
        });
        menuFuncionario.add(mitemCadastrar);

        jMenuBar1.add(menuFuncionario);

        menuProduto.setText("Produto");

        View_Prod.setText("Visualizar Produto");
        View_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_ProdActionPerformed(evt);
            }
        });
        menuProduto.add(View_Prod);

        jMenuBar1.add(menuProduto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTit, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(panelFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemCadastrarActionPerformed
        new NewProduto().setVisible(true);
    }//GEN-LAST:event_mitemCadastrarActionPerformed

    private void View_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_ProdActionPerformed
        conecta.conectaBanco(2);
        conecta.identificaProd(sliQuant.getValue());
        prod.NewProduto(conecta.getAnome(), conecta.getApreço(), conecta.getAestoq(), conecta.getAdescr());
        pv.VisualizarProd(prod);
        pv.setVisible(true);
        conecta.fechaBanco();
    }//GEN-LAST:event_View_ProdActionPerformed

    private void FecharItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharItemActionPerformed
        dispose();
    }//GEN-LAST:event_FecharItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProd_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProd_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProd_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProd_Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProd_Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FecharItem;
    private javax.swing.JMenuItem View_Prod;
    private javax.swing.JButton buttonFiltrar;
    private javax.swing.JComboBox<String> cbDeparts;
    private javax.swing.JLabel imagemTeste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labFiltro;
    private javax.swing.JLabel labelQuant;
    private javax.swing.JLabel labelVMax;
    private javax.swing.JLabel labelVMin;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenuItem mitemCadastrar;
    private javax.swing.JPanel panelFiltrar;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel panelTit;
    private javax.swing.JSlider sliQuant;
    private javax.swing.JSpinner spiVMax;
    private javax.swing.JSpinner spiVMin;
    // End of variables declaration//GEN-END:variables
}
