package View;

import Conexões.MySQL;
import Objetos.Pessoa;
import java.util.EmptyStackException;

/**
 *
 * @author eduar
 */
public class NewClient extends javax.swing.JFrame {

    MySQL conectar = new MySQL(); //acessar os métodos de conexao com o banco
    Pessoa nClient = new Pessoa(); //acessar os atributos da classe cliente
    
    String mês;
    
    public NewClient() {
        initComponents();
        
        setDefaultCloseOperation(NewProduto.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NomeCompleto = new javax.swing.JLabel();
        nomecTxt = new javax.swing.JTextField();
        labCPF = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JFormattedTextField();
        DataNascença = new javax.swing.JLabel();
        monthTxt = new javax.swing.JComboBox<>();
        dayTxt = new javax.swing.JComboBox<>();
        Estado = new javax.swing.JLabel();
        estadoTxt = new javax.swing.JComboBox<>();
        Cidade = new javax.swing.JLabel();
        endeTxt = new javax.swing.JTextField();
        Endereço = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        Senha = new javax.swing.JLabel();
        SenhaConf = new javax.swing.JLabel();
        passwTxt = new javax.swing.JPasswordField();
        cpasswTxt = new javax.swing.JPasswordField();
        yearTxt = new javax.swing.JComboBox<>();
        cadastrarSe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(233, 84));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(109, 98, 131));
        jPanel2.setPreferredSize(new java.awt.Dimension(506, 600));

        NomeCompleto.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        NomeCompleto.setForeground(new java.awt.Color(20, 20, 20));
        NomeCompleto.setText("Nome Completo:");

        nomecTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N

        labCPF.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        labCPF.setForeground(new java.awt.Color(20, 20, 20));
        labCPF.setText("CPF:");

        try {
            cpfTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 13)); // NOI18N
        cpfTxt.setPreferredSize(new java.awt.Dimension(64, 30));

        DataNascença.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        DataNascença.setForeground(new java.awt.Color(20, 20, 20));
        DataNascença.setText("Data de Nascença:");

        monthTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 13)); // NOI18N
        monthTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        monthTxt.setToolTipText("Mês");
        monthTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        monthTxt.setName("Mês"); // NOI18N
        monthTxt.setPreferredSize(new java.awt.Dimension(69, 30));

        dayTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 12)); // NOI18N
        dayTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dayTxt.setMinimumSize(new java.awt.Dimension(55, 30));
        dayTxt.setPreferredSize(new java.awt.Dimension(57, 30));

        Estado.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        Estado.setForeground(new java.awt.Color(20, 20, 20));
        Estado.setText("Estado:");

        estadoTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 14)); // NOI18N
        estadoTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        estadoTxt.setPreferredSize(new java.awt.Dimension(69, 30));

        Cidade.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        Cidade.setForeground(new java.awt.Color(20, 20, 20));
        Cidade.setText("Cidade:");

        endeTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N

        Endereço.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        Endereço.setForeground(new java.awt.Color(20, 20, 20));
        Endereço.setText("Endereço:");

        cityTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N

        Email.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        Email.setForeground(new java.awt.Color(20, 20, 20));
        Email.setText("E-mail:");

        emailTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N

        Senha.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        Senha.setForeground(new java.awt.Color(20, 20, 20));
        Senha.setText("Senha:");

        SenhaConf.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        SenhaConf.setForeground(new java.awt.Color(20, 20, 20));
        SenhaConf.setText("Confirmação de Senha:");

        passwTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N

        cpasswTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N
        cpasswTxt.setToolTipText("");

        yearTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 14)); // NOI18N
        yearTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930" }));
        yearTxt.setMinimumSize(new java.awt.Dimension(60, 30));
        yearTxt.setPreferredSize(new java.awt.Dimension(60, 30));

        cadastrarSe.setBackground(new java.awt.Color(217, 182, 255));
        cadastrarSe.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        cadastrarSe.setForeground(new java.awt.Color(20, 20, 20));
        cadastrarSe.setText("Se cadastrar");
        cadastrarSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NomeCompleto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomecTxt))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cadastrarSe, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labCPF)
                                .addGap(1, 1, 1)
                                .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(DataNascença)
                                .addGap(1, 1, 1)
                                .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Estado)
                                .addGap(9, 9, 9)
                                .addComponent(estadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(Cidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Endereço)
                            .addComponent(endeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Email)
                                .addGap(9, 9, 9)
                                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Senha)
                            .addComponent(passwTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SenhaConf)
                            .addComponent(cpasswTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(dayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(4, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCompleto)
                    .addComponent(nomecTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labCPF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(DataNascença))
                    .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Estado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(estadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Cidade))
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(Endereço)
                .addGap(6, 6, 6)
                .addComponent(endeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Email))
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(Senha)
                .addGap(5, 5, 5)
                .addComponent(passwTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(SenhaConf)
                .addGap(3, 3, 3)
                .addComponent(cpasswTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cadastrarSe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(394, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\SingIn-NewClient\\SingIn1.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarSeActionPerformed
        try {
            //<editor-fold defaultstate="collapsed" desc="Conversão de meses (Nome >> Número)">
            switch(monthTxt.getSelectedIndex()){
                case 0:     mês = "1";  break;
                case 1:     mês = "2";  break;
                case 2:     mês = "3";  break;
                case 3:     mês = "4";  break;
                case 4:     mês = "5";  break;
                case 5:     mês = "6";  break;
                case 6:     mês = "7";  break;
                case 7:     mês = "8";  break;
                case 8:     mês = "9";  break;
                case 9:     mês = "10"; break;
                case 10:    mês = "11"; break;
                case 11:    mês = "12"; break;
            }
            //</editor-fold>

            // Método para fazer as variaveis receberem seus valores
            nClient.novoCliente(nomecTxt.getText(),
                yearTxt.getSelectedItem()+"-"+mês+"-"+dayTxt.getSelectedItem(),
                cpfTxt.getText(), 
                (String) estadoTxt.getSelectedItem(),
                cityTxt.getText(),
                endeTxt.getText(),
                emailTxt.getText(),
                new String (passwTxt.getPassword()));

            if (new String (passwTxt.getPassword()).equals(new String (cpasswTxt.getPassword()))) {
                System.out.println("Senha confirmada");
            } else {
                throw new EmptyStackException();
            }

            conectar.conectaBanco(1);
            String comando = "call hs_pess.insertCliente("
            + "'" + nClient.getNome() + "',"
            + "'" + nClient.getDataN() + "',"
            + "'" + nClient.getCpf() + "',"
            + "'" + nClient.getEstado() + "',"
            + "'" + nClient.getCity() + "',"
            + "'" + nClient.getEnde() + "',"
            + "'" + nClient.getEmail() + "',"
            + "'" + nClient.getPassw() + "'"
            + ");";

            System.out.println(nClient.getEstado());
            this.conectar.cadastrarSQL(comando, 1);

            new SingIn().setVisible(true);
            System.out.println("Cliente cadastrado!");
            dispose();

        } catch (NullPointerException e) {
            System.out.println("Algum campo não foi preenchido.");
        } catch(EmptyStackException e) {
            System.out.println("Senha não confirmada.");
            passwTxt.setText("");
            cpasswTxt.setText("");
        }

    }//GEN-LAST:event_cadastrarSeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cidade;
    private javax.swing.JLabel DataNascença;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereço;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel NomeCompleto;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel SenhaConf;
    private javax.swing.JButton cadastrarSe;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JPasswordField cpasswTxt;
    private javax.swing.JFormattedTextField cpfTxt;
    private javax.swing.JComboBox<String> dayTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField endeTxt;
    private javax.swing.JComboBox<String> estadoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labCPF;
    private javax.swing.JComboBox<String> monthTxt;
    private javax.swing.JTextField nomecTxt;
    private javax.swing.JPasswordField passwTxt;
    private javax.swing.JComboBox<String> yearTxt;
    // End of variables declaration//GEN-END:variables
}
