package View;

import Conexões.MySQL;
import Objetos.Produto;
import java.util.EmptyStackException;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class NewProduto extends javax.swing.JFrame {

    int depart;
    
    MySQL conectar = new MySQL();
    Produto nProd = new Produto();
    
    /**
     * Creates new form NewProduto
     */
    public NewProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nwprodLab = new javax.swing.JLabel();
        nmprodLab = new javax.swing.JLabel();
        nmprodTxt = new javax.swing.JTextField();
        labPVenda = new javax.swing.JLabel();
        spiPVenda = new javax.swing.JSpinner();
        labPCusto = new javax.swing.JLabel();
        spiPCusto = new javax.swing.JSpinner();
        labEstoq = new javax.swing.JLabel();
        spiEstoq = new javax.swing.JSpinner();
        labDepart = new javax.swing.JLabel();
        cbDepart = new javax.swing.JComboBox<>();
        imageLab = new javax.swing.JLabel();
        imageTxt = new javax.swing.JTextField();
        butAdicionar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProds = new javax.swing.JTable();
        labBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(433, 59));
        setMaximumSize(new java.awt.Dimension(500, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nwprodLab.setFont(new java.awt.Font("Traveling _Typewriter", 1, 24)); // NOI18N
        nwprodLab.setText("Novo Produto");

        nmprodLab.setFont(new java.awt.Font("Traveling _Typewriter", 1, 17)); // NOI18N
        nmprodLab.setText("Nome do Produto:");

        nmprodTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        nmprodTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmprodTxtActionPerformed(evt);
            }
        });

        labPVenda.setFont(new java.awt.Font("Traveling _Typewriter", 1, 17)); // NOI18N
        labPVenda.setText("Preço de Venda:");

        spiPVenda.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        spiPVenda.setModel(new javax.swing.SpinnerNumberModel(300, 300, 7700, 100));
        spiPVenda.setPreferredSize(new java.awt.Dimension(100, 30));

        labPCusto.setFont(new java.awt.Font("Traveling _Typewriter", 1, 17)); // NOI18N
        labPCusto.setText("Preço de Custo:");

        spiPCusto.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        spiPCusto.setModel(new javax.swing.SpinnerNumberModel(7700, 300, 8000, 100));
        spiPCusto.setPreferredSize(new java.awt.Dimension(100, 30));

        labEstoq.setFont(new java.awt.Font("Traveling _Typewriter", 1, 17)); // NOI18N
        labEstoq.setText("Estoque:");

        spiEstoq.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        spiEstoq.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        spiEstoq.setPreferredSize(new java.awt.Dimension(100, 30));

        labDepart.setFont(new java.awt.Font("Traveling _Typewriter", 1, 17)); // NOI18N
        labDepart.setText("Departamento:");

        cbDepart.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        cbDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armas", "Munições", "Consumíveis", "Especiais" }));
        cbDepart.setPreferredSize(new java.awt.Dimension(69, 30));
        cbDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartActionPerformed(evt);
            }
        });

        imageLab.setFont(new java.awt.Font("Traveling _Typewriter", 1, 17)); // NOI18N
        imageLab.setText("Endereço Imagem:");

        imageTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        imageTxt.setPreferredSize(new java.awt.Dimension(71, 30));

        butAdicionar.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N
        butAdicionar.setText("Adicionar");
        butAdicionar.setPreferredSize(new java.awt.Dimension(150, 45));
        butAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdicionarActionPerformed(evt);
            }
        });

        butCancelar.setFont(new java.awt.Font("Traveling _Typewriter", 0, 18)); // NOI18N
        butCancelar.setText("Cancelar");
        butCancelar.setPreferredSize(new java.awt.Dimension(150, 45));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(488, 180));

        tabProds.setAutoCreateRowSorter(true);
        tabProds.setFont(new java.awt.Font("Traveling _Typewriter", 0, 14)); // NOI18N
        tabProds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {"4", null, null, null},
                {"5", null, null, null},
                {"6", null, null, null},
                {"7", null, null, null},
                {"8", null, null, null},
                {"9", null, null, null},
                {"10", null, null, null}
            },
            new String [] {
                "N. Produto", "Nome do Produto", "Preço do Produto", "Categoria de Produto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProds.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabProds);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nmprodLab)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labPVenda)
                        .addComponent(labPCusto))
                    .addComponent(imageLab)
                    .addComponent(labEstoq)
                    .addComponent(labDepart))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spiPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmprodTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(spiPCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiEstoq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(butAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(nwprodLab)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nwprodLab)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmprodLab)
                    .addComponent(nmprodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPVenda)
                    .addComponent(spiPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spiPCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labPCusto))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spiEstoq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labEstoq))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDepart)
                    .addComponent(cbDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageLab)
                    .addComponent(imageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 650));

        labBG.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Desktop\\RPG\\Sessions\\Fichas\\Imagens extras\\Papel Velho\\SPapelVelho 1 - Copia.png")); // NOI18N
        labBG.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(labBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmprodTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmprodTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmprodTxtActionPerformed

    private void butAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdicionarActionPerformed
        // Método para fazer as variaveis receberem seus valores
        try {
            spiPVenda.commitEdit();
            spiPCusto.commitEdit();
            spiEstoq.commitEdit();
        } catch ( java.text.ParseException e ) {
            System.out.println("ERRO");
        }
        System.out.println("Pega Spinners");
        
        System.out.println("Começa Processo Botão");
        try {
            
//            switch (cbDepart.getSelectedIndex()) {
//                case 1:
//                    depart = 1;
//                    break;
//                case "Munições":
//                    depart = 2;
//                    break;
//                case "Consumíveis":
//                    depart = 3;
//                    break;
//                case "Especiais":
//                    depart = 4;
//                    break;
//            }
//            System.out.println("DepartInt");
            
            nProd.NewProduto(nmprodTxt.getText(), 
            (int) spiPVenda.getValue(),
            (int) spiPCusto.getValue(),
            (int) spiEstoq.getValue(),
            cbDepart.getSelectedIndex() + 1,
            imageTxt.getText());
            System.out.println("Fazendo Produto-obj");
            
            conectar.conectaBanco(2);
            String comando = "call hs_prod.insertProduto("
                + "'" + nProd.getNome() + "',"
                + "" + nProd.getPvenda() + ","
                + "" + nProd.getPcusto() + ","
                + "" + nProd.getEstoque() + ","
                + "" + nProd.getDepart() + ""
            + ");";
            
            System.out.println("Cria Comando");
        
            conectar.cadastrarSQL(comando, 2);
            System.out.println("Manda Comando");
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Algum campo não foi preenchido.");
        } catch(EmptyStackException e) {
            JOptionPane.showMessageDialog(null, "Senha não confirmada.");
        }
        
    }//GEN-LAST:event_butAdicionarActionPerformed

    private void cbDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdicionar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JComboBox<String> cbDepart;
    private javax.swing.JLabel imageLab;
    private javax.swing.JTextField imageTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labBG;
    private javax.swing.JLabel labDepart;
    private javax.swing.JLabel labEstoq;
    private javax.swing.JLabel labPCusto;
    private javax.swing.JLabel labPVenda;
    private javax.swing.JLabel nmprodLab;
    private javax.swing.JTextField nmprodTxt;
    private javax.swing.JLabel nwprodLab;
    private javax.swing.JSpinner spiEstoq;
    private javax.swing.JSpinner spiPCusto;
    private javax.swing.JSpinner spiPVenda;
    private javax.swing.JTable tabProds;
    // End of variables declaration//GEN-END:variables
}
