package View;

import Conexões.MySQL;
import Objetos.Produto;
import java.awt.event.WindowEvent;
import java.util.EmptyStackException;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class NewProduto extends javax.swing.JFrame {

    int depart;
    
    MySQL conectar = new MySQL();
    Produto nProd = new Produto();
    
    /**
     * Creates new form NovoProduto
     */
    public NewProduto() {
        initComponents();
        
        setDefaultCloseOperation(NewProduto.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        butAdicionar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nmprodLab = new javax.swing.JLabel();
        nmprodTxt = new javax.swing.JTextField();
        labPVenda = new javax.swing.JLabel();
        spiPVenda = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        labPCusto = new javax.swing.JLabel();
        spiPCusto = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        labEstoq = new javax.swing.JLabel();
        spiEstoq = new javax.swing.JSpinner();
        labDepart = new javax.swing.JLabel();
        cbDepart = new javax.swing.JComboBox<>();
        imageLab = new javax.swing.JLabel();
        imageTxt = new javax.swing.JTextField();
        labDescr = new javax.swing.JLabel();
        descrTxtar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(433, 59));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(20, 20, 20));
        jPanel3.setForeground(new java.awt.Color(20, 20, 20));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 107));

        butAdicionar.setBackground(new java.awt.Color(217, 182, 255));
        butAdicionar.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        butAdicionar.setForeground(new java.awt.Color(20, 20, 20));
        butAdicionar.setText("Adicionar");
        butAdicionar.setMargin(new java.awt.Insets(5, 14, 0, 14));
        butAdicionar.setPreferredSize(new java.awt.Dimension(150, 45));
        butAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdicionarActionPerformed(evt);
            }
        });

        butCancelar.setBackground(new java.awt.Color(217, 182, 255));
        butCancelar.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        butCancelar.setForeground(new java.awt.Color(20, 20, 20));
        butCancelar.setText("Cancelar");
        butCancelar.setMargin(new java.awt.Insets(5, 14, 0, 14));
        butCancelar.setPreferredSize(new java.awt.Dimension(150, 45));
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\NewProduto\\NewProduto4.png")); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(500, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(butAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 543, 500, -1));

        jPanel2.setBackground(new java.awt.Color(20, 20, 20));
        jPanel2.setForeground(new java.awt.Color(20, 20, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 122));

        jLabel3.setBackground(new java.awt.Color(187, 187, 187));
        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(217, 182, 255));
        jLabel3.setText("Novo Produto");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\NewProduto\\NewProduto2.png")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jPanel1.setBackground(new java.awt.Color(109, 98, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 528));

        nmprodLab.setFont(new java.awt.Font("Sitka Small", 1, 17)); // NOI18N
        nmprodLab.setText("Nome do Produto:");

        nmprodTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        nmprodTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmprodTxtActionPerformed(evt);
            }
        });

        labPVenda.setFont(new java.awt.Font("Sitka Small", 1, 17)); // NOI18N
        labPVenda.setText("Preço de Venda:");

        spiPVenda.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        spiPVenda.setModel(new javax.swing.SpinnerNumberModel(4000, 100, 8000, 100));
        spiPVenda.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel1.setText("ptas");

        labPCusto.setFont(new java.awt.Font("Sitka Small", 1, 17)); // NOI18N
        labPCusto.setText("Preço de Custo:");

        spiPCusto.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        spiPCusto.setModel(new javax.swing.SpinnerNumberModel(4000, 100, 8000, 100));
        spiPCusto.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel2.setText("ptas");
        jLabel2.setPreferredSize(new java.awt.Dimension(29, 20));

        labEstoq.setFont(new java.awt.Font("Sitka Small", 1, 17)); // NOI18N
        labEstoq.setText("Estoque:");

        spiEstoq.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        spiEstoq.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        spiEstoq.setPreferredSize(new java.awt.Dimension(100, 30));

        labDepart.setFont(new java.awt.Font("Sitka Small", 1, 17)); // NOI18N
        labDepart.setText("Departamento:");

        cbDepart.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        cbDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armas", "Munições", "Consumíveis", "Mapa", "Especiais" }));
        cbDepart.setPreferredSize(new java.awt.Dimension(69, 30));
        cbDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartActionPerformed(evt);
            }
        });

        imageLab.setFont(new java.awt.Font("Sitka Small", 1, 17)); // NOI18N
        imageLab.setText("Endereço Imagem:");

        imageTxt.setFont(new java.awt.Font("Traveling _Typewriter", 0, 17)); // NOI18N
        imageTxt.setPreferredSize(new java.awt.Dimension(71, 30));

        labDescr.setFont(new java.awt.Font("Sitka Small", 1, 17)); // NOI18N
        labDescr.setText("Descrição:");

        descrTxtar.setColumns(20);
        descrTxtar.setFont(new java.awt.Font("Traveling _Typewriter", 0, 14)); // NOI18N
        descrTxtar.setLineWrap(true);
        descrTxtar.setRows(5);
        descrTxtar.setPreferredSize(new java.awt.Dimension(232, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labDescr)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmprodLab)
                            .addComponent(labPVenda)
                            .addComponent(imageLab)
                            .addComponent(labEstoq)
                            .addComponent(labDepart)
                            .addComponent(labPCusto))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nmprodTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spiPCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spiEstoq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imageTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spiPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(cbDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(descrTxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmprodLab)
                    .addComponent(nmprodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPVenda)
                    .addComponent(spiPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spiPCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labPCusto)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spiEstoq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labEstoq))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDepart)
                    .addComponent(cbDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageLab)
                    .addComponent(imageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(labDescr)
                .addGap(4, 4, 4)
                .addComponent(descrTxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 500, 421));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimpaCampos() {
        nmprodTxt.setText("");
        spiPVenda.setValue(4000);
        spiPCusto.setValue(4000);
        spiEstoq.setValue(1);
        cbDepart.setSelectedIndex(0);
        imageTxt.setText("");
        descrTxtar.setText("");
    }
    
    //<editor-fold defaultstate="collapsed" desc="Método não utilizado">
    private void nmprodTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmprodTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmprodTxtActionPerformed
    //</editor-fold>
    
    private void butAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdicionarActionPerformed
        // Método para fazer as variaveis receberem seus valores
        try {
            spiPVenda.commitEdit();
            spiPCusto.commitEdit();
            spiEstoq.commitEdit();
        } catch ( java.text.ParseException e ) {
            System.out.println("ERRO");
        }
        
        
        try {
            nProd.NovoProduto(nmprodTxt.getText(), 
            (int) spiPVenda.getValue(),
            (int) spiPCusto.getValue(),
            (int) spiEstoq.getValue(),
            cbDepart.getSelectedIndex() + 1,
            imageTxt.getText(),
            descrTxtar.getText());
            
            conectar.conectaBanco(2);
            String comando = "call hs_prod.insertProduto("
                + "'" + nProd.getNome()    + "',"
                + ""  + nProd.getPvenda()  +  ","
                + ""  + nProd.getPcusto()  +  ","
                + ""  + nProd.getEstoque() +  ","
                + ""  + nProd.getDepart()  +  ","
                + "'" + nProd.getDescr()   + "'"
            + ");";
        
            conectar.cadastrarSQL(comando, 2);
            
            LimpaCampos();
            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Algum campo não foi preenchido.");
        } catch(EmptyStackException e) {
            JOptionPane.showMessageDialog(null, "Senha não confirmada.");
        }
        
    }//GEN-LAST:event_butAdicionarActionPerformed

    //<editor-fold defaultstate="collapsed" desc="Método não utilizado">
    private void cbDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartActionPerformed
         //TODO add your handling code here:
    }//GEN-LAST:event_cbDepartActionPerformed
    //</editor-fold>
    
    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_butCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdicionar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JComboBox<String> cbDepart;
    private javax.swing.JTextArea descrTxtar;
    private javax.swing.JLabel imageLab;
    private javax.swing.JTextField imageTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labDepart;
    private javax.swing.JLabel labDescr;
    private javax.swing.JLabel labEstoq;
    private javax.swing.JLabel labPCusto;
    private javax.swing.JLabel labPVenda;
    private javax.swing.JLabel nmprodLab;
    private javax.swing.JTextField nmprodTxt;
    private javax.swing.JSpinner spiEstoq;
    private javax.swing.JSpinner spiPCusto;
    private javax.swing.JSpinner spiPVenda;
    // End of variables declaration//GEN-END:variables
}
