package View;

import Objetos.Produto;

/**
 *
 * @author eduar
 */
public class Prod_View extends javax.swing.JFrame {

    /**
     * Creates new form Prod_View
     */
    public Prod_View() {
        initComponents();
    }

    Comprar_Prod buy = new Comprar_Prod();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBack = new javax.swing.JPanel();
        Voltar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labEstoq = new javax.swing.JLabel();
        labPreço = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textaDescr = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        panelComprar = new javax.swing.JPanel();
        butComprar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(20, 20, 20));
        setLocation(new java.awt.Point(486, 107));
        setMaximumSize(new java.awt.Dimension(646, 579));
        setMinimumSize(new java.awt.Dimension(646, 579));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(646, 579));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBack.setBackground(new java.awt.Color(20, 20, 20));
        panelBack.setPreferredSize(new java.awt.Dimension(646, 58));

        Voltar.setBackground(new java.awt.Color(217, 182, 255));
        Voltar.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(20, 20, 20));
        Voltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Downloads\\seta-voltar.png")); // NOI18N
        Voltar.setText("Voltar");
        Voltar.setAlignmentX(1.0F);
        Voltar.setAlignmentY(1.0F);
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Voltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Voltar.setIconTextGap(8);
        Voltar.setMargin(new java.awt.Insets(2, 5, 0, 5));
        Voltar.setPreferredSize(new java.awt.Dimension(140, 35));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\View_Prod\\View_Prod1.png")); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 4));

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addGroup(panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBackLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(537, 537, 537))
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE))
        );

        getContentPane().add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        panelProd.setBackground(new java.awt.Color(109, 98, 131));
        panelProd.setPreferredSize(new java.awt.Dimension(652, 575));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\View_Prod\\View_Prod.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(230, 148, 255), new java.awt.Color(240, 190, 255), new java.awt.Color(204, 116, 231), new java.awt.Color(211, 147, 230)));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 300));

        jPanel2.setBackground(new java.awt.Color(217, 182, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(230, 148, 255), new java.awt.Color(240, 190, 255), new java.awt.Color(204, 116, 231), new java.awt.Color(211, 147, 230)));
        jPanel2.setPreferredSize(new java.awt.Dimension(316, 300));

        labNome.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        labNome.setForeground(new java.awt.Color(20, 20, 20));
        labNome.setText("Stock (Red9)");

        jLabel3.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 20, 20));
        jLabel3.setText("Estoque:");

        labEstoq.setFont(new java.awt.Font("Traveling _Typewriter", 1, 14)); // NOI18N
        labEstoq.setForeground(new java.awt.Color(20, 20, 20));
        labEstoq.setText("20");

        labPreço.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        labPreço.setForeground(new java.awt.Color(20, 20, 20));
        labPreço.setText("1400");

        jLabel6.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 20, 20));
        jLabel6.setText("Descrição do Produto:");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(237, 137));

        textaDescr.setColumns(20);
        textaDescr.setFont(new java.awt.Font("Traveling _Typewriter", 0, 14)); // NOI18N
        textaDescr.setLineWrap(true);
        textaDescr.setRows(5);
        textaDescr.setWrapStyleWord(true);
        textaDescr.setPreferredSize(new java.awt.Dimension(237, 150));
        jScrollPane1.setViewportView(textaDescr);

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 20, 20));
        jLabel7.setText("ptas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labEstoq)
                        .addGap(20, 20, 20))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labPreço)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labNome)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labPreço)
                        .addComponent(jLabel3)
                        .addComponent(labEstoq))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelProdLayout = new javax.swing.GroupLayout(panelProd);
        panelProd.setLayout(panelProdLayout);
        panelProdLayout.setHorizontalGroup(
            panelProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelProdLayout.setVerticalGroup(
            panelProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProdLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(panelProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 646, 392));

        panelComprar.setBackground(new java.awt.Color(20, 20, 20));
        panelComprar.setPreferredSize(new java.awt.Dimension(646, 125));

        butComprar.setBackground(new java.awt.Color(217, 182, 255));
        butComprar.setFont(new java.awt.Font("Traveling _Typewriter", 1, 18)); // NOI18N
        butComprar.setForeground(new java.awt.Color(20, 20, 20));
        butComprar.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Downloads\\cesta-de-compras.png")); // NOI18N
        butComprar.setText("Comprar");
        butComprar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        butComprar.setIconTextGap(8);
        butComprar.setPreferredSize(new java.awt.Dimension(170, 45));
        butComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butComprarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(217, 182, 255));
        jButton2.setFont(new java.awt.Font("Traveling _Typewriter", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(20, 20, 20));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Downloads\\adicionar-ao-carrinho.png")); // NOI18N
        jButton2.setText("Carrinho");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setIconTextGap(8);
        jButton2.setPreferredSize(new java.awt.Dimension(170, 45));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\eduar\\Documents\\Facens\\2º Semestre\\Linguagem de Programação - Prof. Márcio\\Hey-Stranger\\src\\Imagens\\Telas_Views\\View_Prod\\View_Prod1.png")); // NOI18N

        javax.swing.GroupLayout panelComprarLayout = new javax.swing.GroupLayout(panelComprar);
        panelComprar.setLayout(panelComprarLayout);
        panelComprarLayout.setHorizontalGroup(
            panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComprarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(butComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelComprarLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelComprarLayout.setVerticalGroup(
            panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(panelComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Método não usado"> 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    // </editor-fold> 
    
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
         dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void butComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butComprarActionPerformed
        buy.IniciarTela(labNome.getText(), labPreço.getText(), textaDescr.getText());
        buy.setVisible(true);
    }//GEN-LAST:event_butComprarActionPerformed

    public void VisualizarProd(Produto p) {
        labNome.setText(p.getNome());
        labPreço.setText(Integer.toString((int) p.getPvenda()));
        labEstoq.setText(Integer.toString((int) p.getEstoque()));
        textaDescr.setText(p.getDescr());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prod_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prod_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prod_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prod_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prod_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JButton butComprar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labEstoq;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labPreço;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelComprar;
    private javax.swing.JPanel panelProd;
    private javax.swing.JTextArea textaDescr;
    // End of variables declaration//GEN-END:variables
}
